### ISSUE TITLE
Add support for files where the contacts are not separated by an empty line.

### ISSUE THREAD

**Issue by meblum** [EFFKAY2/ContactSplitMergeTool#2]
Currently, the contacts are extracted by checking for an empty line.
Should be changed to check for "begin vcard" and "end vcard". This will enable input of a file which is not separated by an empty line.

**Comment by mordechaim** [comment]
Also it currently assumes the name is always on line 4, which is a dangerous assumption. You should check for `N;` or `FN;`

**Comment by meblum** [comment]
Will update it with regex.

**Comment by mordechaim** [comment]
Probably a simple `StartsWith()` is enough.

**Comment by meblum** [comment]
Right, Never knew of this method.

**Comment by meblum** [comment]
Updated it. also changed from string to StringBuilder.
